### PR TITLE
Vaisala met

### PR DESCRIPTION
**Pull request by odemeo-usgs**
Add Vaisala WXT536 to stglib

### CODE REVIEW

**Comment by dnowacki-usgs** [comment]
Hi Olivia, this is looking good. Can you provide a test dataset and ideally add it to the test suite? I can help you with this, but you can check in https://github.com/USGS-CMG/stglib/tree/master/stglib/tests for examples.

**Comment by dnowacki-usgs** [comment]
Awesome, thanks! Two more things: test data should be stored using Git LFS, and please run the files you changed through the "black" code formatter. Really appreciate this PR!

**Comment by odemeo-usgs** [comment]
Sorry, I have no idea what either of those things mean.  What is Git LFS and the black code formatter?

Olivia De Meo
Technical Information Specialist
US Geological Survey, Department of Interior
Woods Hole Coastal and Marine Science Center
384 Woods Hole Road, Woods Hole, MA 02543

From: Dan Nowacki ***@***.***>
Sent: Tuesday, March 22, 2022 3:50 PM
To: USGS-CMG/stglib ***@***.***>
Cc: De Meo, Olivia A ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [USGS-CMG/stglib] Vaisala met (PR #61)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Awesome, thanks! Two more things: test data should be stored using Git LFS, and please run the files you changed through the "black" code formatter. Really appreciate this PR!

-

**Comment by odemeo-usgs** [comment]
Hi Dan,

I added a dataset and made edits to test_scripts.py.  I wasn't sure if anything needed to be added to test_stglib.py?  I committed the changes and pushed to github.

Olivia

Olivia De Meo
Technical Information Specialist
US Geological Survey, Department of Interior
Woods Hole Coastal and Marine Science Center
384 Woods Hole Road, Woods Hole, MA 02543

From: Dan Nowacki ***@***.***>
Sent: Monday, March 21, 2022 3:59 PM
To: USGS-CMG/stglib ***@***.***>
Cc: De Meo, Olivia A ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [USGS-CMG/stglib] Vaisala met (PR #61)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Hi Olivia, this is looking good. Can you provide a test dataset and ideally add it to the test suite? I can help you with this, but you can check in https://github.com/USGS-CMG/stglib/tree/master/stglib/tests<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSGS-CMG%2Fstglib%2Ftree%2Fmaster%2Fstglib%2Ftests&data=04%7C01%7Codemeo%40usgs.gov%7Cc752a79bade34a7b8a6408da0b756f8d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637834896266068988%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KTKZMo7C12B0Ye6zE2ELUUp4x%2F7it0sCMerFHV2KCCQ%3D&reserved=0> for examples.

-

**Comment by odemeo-usgs** [comment]
Hi Dan,

I think I figured it out and blacked the code and added Git LFS.  Let me know if it didn't work!

Olivia

Olivia De Meo
Technical Information Specialist
US Geological Survey, Department of Interior
Woods Hole Coastal and Marine Science Center
384 Woods Hole Road, Woods Hole, MA 02543

From: Dan Nowacki ***@***.***>
Sent: Tuesday, March 22, 2022 3:50 PM
To: USGS-CMG/stglib ***@***.***>
Cc: De Meo, Olivia A ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [USGS-CMG/stglib] Vaisala met (PR #61)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Awesome, thanks! Two more things: test data should be stored using Git LFS, and please run the files you changed through the "black" code formatter. Really appreciate this PR!

-

**Pull request merged**
